repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-docstring-first
    - id: detect-private-key


- repo: local
  hooks:
  - id: lint
    name: Lint
    entry: make lint
    types: [python]
    language: system

  # - id: mypy
  #   name: Mypy
  #   entry: make mypy
  #   types: [python]
  #   language: system
